blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DiscussÃ£o Geral
    url: https://github.com/pachicodes/papo-devrel/discussions
    about: Para discussÃµes sobre o projeto, sugestÃµes de episÃ³dios ou feedback geral
  - name: ğŸ› Reportar Bug
    url: https://github.com/pachicodes/papo-devrel/issues/new
    about: Para reportar problemas tÃ©cnicos ou bugs no repositÃ³rio
