blank_issues_enabled: false
contact_links:
  - name: ğŸ“ SugestÃ£o de EpisÃ³dio
    url: https://github.com/pachicodes/papo-devrel/issues/new/choose
    about: Para sugerir novos temas ou convidados para o Papo DevRel
  - name: ğŸ”§ Melhorias no Processo
    url: https://github.com/pachicodes/papo-devrel/issues/new
    about: Para sugerir melhorias nos templates, roteiros ou processo de produÃ§Ã£o